# Generated by Django 5.2.17 on 2026-10-01 06:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current / Checking Account'), ('FIXED_DEPOSIT', 'Fixed Deposit Account'), ('RECURRING_DEPOSIT', 'Recurring Deposit Account')], default='SAVINGS', max_length=25)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('3.50'), max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('FROZEN', 'Frozen / Blocked'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_IN', 'Transfer Received'), ('TRANSFER_OUT', 'Transfer Sent'), ('LOAN_DISBURSEMENT', 'Loan Disbursed'), ('EMI_PAYMENT', 'Loan EMI Repayment'), ('FD_INTEREST', 'Fixed Deposit Interest')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account')),
                ('recipient_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='banking.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(default='Apex National Bank', max_length=150)),
                ('ifsc_code', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='accounts.customerprofile')),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['beneficiary_name'],
                'unique_together': {('customer', 'account_number')},
            },
        ),
    ]
