# Generated by Django 5.2.17 on 2026-10-01 06:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan / Mortgage'), ('VEHICLE', 'Auto / Vehicle Loan'), ('EDUCATION', 'Education Loan'), ('BUSINESS', 'Small Business Loan')], default='PERSONAL', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate percentage', max_digits=5)),
                ('tenure_months', models.PositiveIntegerField(help_text='Repayment term in months')),
                ('monthly_emi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed & Active'), ('CLOSED', 'Closed / Fully Paid')], default='PENDING', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.customerprofile')),
                ('disbursed_to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to='banking.account')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_component', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('interest_component', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.transaction')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
    ]
