# Generated by Django 5.2.17 on 2026-10-01 06:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('6.50'), max_digits=5)),
                ('tenure_months', models.PositiveIntegerField(help_text='Tenure in months')),
                ('maturity_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('CLOSED_PREMATURE', 'Closed Prematurely')], default='ACTIVE', max_length=25)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('maturity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposits', to='accounts.customerprofile')),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_fds', to='banking.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('5.80'), max_digits=5)),
                ('tenure_months', models.PositiveIntegerField()),
                ('installments_paid', models.PositiveIntegerField(default=1)),
                ('total_deposited', models.DecimalField(decimal_places=2, max_digits=16)),
                ('maturity_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('CLOSED_PREMATURE', 'Closed Prematurely')], default='ACTIVE', max_length=25)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('maturity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_deposits', to='accounts.customerprofile')),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_rds', to='banking.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
